spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/operations_db?options=-c%20TimeZone=UTC
    username: operations_user
    password: operations_pass
    driver-class-name: org.postgresql.Driver

  jackson:
    time-zone: Asia/Kolkata

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata
